# Generated by Django 4.2 on 2025-11-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
